### PR TITLE
Move tests

### PR DESCRIPTION
**Pull request by nllong**
Move the tests from the tests folder into the specs folder.

### CODE REVIEW

**Comment by tanushree04** [comment]
@nllong I tested this PR on my machine and it looks good, can we merge this?

**Comment by nllong** [comment]
Yep, this is ready to merge. Can you merge?

**Comment by nllong** [comment]
@tanushree04, after you merge this, I'll pull up the changes into #29 and fix the conflicts (if any).

**Comment by tanushree04** [comment]
@nllong This is now merged.

**Pull request merged**
